version: '3'
services:
  proxy:
    image: nginx
    ports:
      - 1180:80
      - 1280:1280
    volumes:
      - ./includes:/etc/nginx/includes
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ./conf.d:/etc/nginx/conf.d
    restart: always
